export const mockRes = {
  recipeName: "Lemon Garlic Roasted Chicken",
  cuisineType: "American",
  servings: 4,
  prepTime: 15,
  cookTime: 50,
  totalTime: 65,
  ingredients: [
    "1 whole chicken (about 1.5kg)",
    "2 lemons, sliced",
    "4 cloves of garlic, minced",
    "2 tablespoons olive oil",
    "1 teaspoon dried oregano",
    "1 teaspoon dried thyme",
    "Salt and black pepper to taste",
  ],
  instructions: [
    "Preheat the oven to 200°C (400°F).",
    "Rinse the chicken and pat it dry with paper towels.",
    "In a small bowl, combine the minced garlic, olive oil, dried oregano, dried thyme, salt, and black pepper.",
    "Rub the garlic mixture all over the chicken, including the cavity and under the skin.",
    "Place the lemon slices inside the chicken cavity.",
    "Tie the chicken legs together using kitchen twine.",
    "Place the chicken on a rack in a roasting pan.",
    "Roast the chicken in the preheated oven for about 40-50 minutes or until the internal temperature reaches 165°F.",
    "Remove the chicken from the oven and let it rest for about 10 minutes before carving.",
    "Serve the lemon garlic roasted chicken with your favorite sides and enjoy!",
  ],
};
